### ISSUE TITLE
Light nodes are not working

### ISSUE THREAD

**Issue by cargopete** [graphops/graphcast-sdk#45] opened 2023-01-16 10:33 UTC
**Describe the bug**
Light nodes not working properly.

**To Reproduce**
- Run a boot node with `cargo run --example ping-pong boot`
- In another terminal window run `cargo run --example ping-pong`
- See error:
```bash
Initialized node handle
Local node peer_id: Ok(
    "16Uiu2HAkwxqx9BagrHAp9vCsuFgErtUbn36PymurVqWARCHWGhkg",
)
Connected to peers: [
    "16Uiu2HAmExzgbXw1quimgxAVRNSSxmrUbM7kunhrDCVdRpmTRdPT",
    "16Uiu2HAmExzgbXw1quimgxAVRNSSxmrUbM7kunhrDCVdRpmTRdPT",
    "16Uiu2HAm8XcSn7UA6Lx6JNSvwxubjo6yMfYC292t7bR2vXcFdiwM",
]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x58 pc=0x1034f23f8]

goroutine 17 [running, locked to thread]:
github.com/waku-org/go-waku/waku/v2/protocol/relay.(*WakuRelay).subscribe(0x0, {0x1400098aac0, 0x1a})
	/Users/petko/.cargo/registry/src/github.com-1ecc6299db9ec823/waku-sys-0.1.0-beta2/vendor/waku/v2/protocol/relay/waku_relay.go:139 +0x28
github.com/waku-org/go-waku/waku/v2/protocol/relay.(*WakuRelay).SubscribeToTopic(0x0, {0x104d14710?, 0x14000044068}, {0x1400098aac0, 0x1a})
	/Users/petko/.cargo/registry/src/github.com-1ecc6299db9ec823/waku-sys-0.1.0-beta2/vendor/waku/v2/protocol/relay/waku_relay.go:229 +0xa0
github.com/waku-org/go-waku/mobile.RelaySubscribe({0x1400098aac0?, 0x102f64784?})
	/Users/petko/.cargo/registry/src/github.com-1ecc6299db9ec823/waku-sys-0.1.0-beta2/vendor/mobile/api_relay.go:97 +0x140
main.waku_relay_subscribe(0x104b3db01?)
	/Users/petko/.cargo/registry/src/github.com-1ecc6299db9ec823/waku-sys-0.1.0-beta2/vendor/library/api_relay.go:54 +0x24
zsh: abort      cargo run --example ping-pong
```

**Expected behavior**
The light node(s) that are started after 1 boot node is running should work fine.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 13.1 (22C65)
 - Rust Version stable-aarch64-apple-darwin

**Comment by axiomatic-aardvark** [comment] 2023-01-16 10:38
This is possibly related to my custom subtopic config work - https://github.com/graphops/graphcast-sdk/pull/39 but at this point I have no idea

**Comment by axiomatic-aardvark** [comment] 2023-01-16 12:25
The issue is arising inside the `waku_relay_subscribe` function from the bindings, and more specifically here:
```
unsafe {
        CStr::from_ptr(waku_sys::waku_relay_enough_peers(
            CString::new(pubsub_topic)
                .expect("CString should build properly from pubsub topic")
                .into_raw(),
        ))
    }
```

**Comment by axiomatic-aardvark** [comment] 2023-01-16 13:24
Some progress has been made - removed `waku_relay_subscribe` from `connect_and_subscribe` and left only `filter_peer_subscriptions`, but now sending messages doesn't work. `relay::waku_relay_publish_message(message, pubsub_topic, timeout)` fails with:
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x102c21088]

goroutine 17 [running, locked to thread]:
github.com/waku-org/go-waku/waku/v2/protocol/relay.(*WakuRelay).PublishToTopic(0x1400020e870?, {0x1044448f0?, 0x14000044068?}, 0x1027e6bbc?, {0x1400003aee0?, 0x1043f2620?})
	/Users/petko/.cargo/registry/src/github.com-1ecc6299db9ec823/waku-sys-0.1.0-beta2/vendor/waku/v2/protocol/relay/waku_relay.go:161 +0x28
github.com/waku-org/go-waku/mobile.relayPublish({{0x140000ac400, 0xf3, 0xf3}, {0x140000f2ae0, 0x2a}, 0x0, 0x63c54ef9, 0x0, 0x0, {}, ...}, ...)
	/Users/petko/.cargo/registry/src/github.com-1ecc6299db9ec823/waku-sys-0.1.0-beta2/vendor/mobile/api_relay.go:46 +0x15c
github.com/waku-org/go-waku/mobile.RelayPublish({0x1400219c700, 0x1b1}, {0x1400003aee0, 0x1a}, 0x5b0080?)
	/Users/petko/.cargo/registry/src/github.com-1ecc6299db9ec823/waku-sys-0.1.0-beta2/vendor/mobile/api_relay.go:56 +0x140
main.waku_relay_publish(0x140000360c0?, 0x0?, 0x0)
	/Users/petko/.cargo/registry/src/github.com-1ecc6299db9ec823/waku-sys-0.1.0-beta2/vendor/library/api_relay.go:22 +0x54
zsh: abort      cargo run --example ping-pong
```

**Comment by axiomatic-aardvark** [comment] 2023-01-16 13:59
Will keep this issue open but rephrase it so that we know it's related to the bindings version bump.

To close it, we need to update the SDK code to work with the latest [waku bindings](https://crates.io/crates/waku-bindings), which in turn are generated from the latest [go-waku](https://github.com/waku-org/go-waku).

**Comment by axiomatic-aardvark** [comment] 2023-01-16 14:03
Also off the back of this we should add integration tests for the SDK to make sure the examples always run (with both boot/light nodes) before merging PRs

**Closed as completed** 2023-01-16 14:14 UTC

**Comment by axiomatic-aardvark** [comment] 2023-01-16 15:41
Two issues coming out of this bug:
- https://github.com/graphops/graphcast-sdk/issues/49
- https://github.com/graphops/graphcast-sdk/issues/48
